# Mostra tabela EPM_FILES_TYPE
GET_EPM_FILES_TYPE = """
SELECT * FROM EPM_FILES_TYPE;
"""

GET_ESTILOS_POR_PROJETO = """
SELECT EM.DESCRICAO AS Estilo, COUNT(A.FK_ESTILO_PRINCIPAL) AS Quantidade
FROM T_ATRACOES A
INNER JOIN T_ESTILOS_MUSICAIS EM ON A.FK_ESTILO_PRINCIPAL = EM.ID
GROUP BY EM.DESCRICAO;"""

GET_USER_POR_LOCAL = """"
SELECT AUD.UF AS UF, COUNT(AUD.ID) AS Quantidade
FROM T_ADMIN_USERS_DADOS AUD
WHERE AUD.UF IS NOT NULL AND AUD.UF != ''
GROUP BY AUD.UF;"""